cat > docker-compose.yml << 'EOF'
version: "3.9"

services:
  database:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  api:
    build: ./api
    depends_on:
      - database
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@database:5432/todo_db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    stdin_open: true
    tty: true

  nginx:
    image: nginx:latest
    depends_on:
      - frontend
      - api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - "80:80"
EOF
